### ISSUE TITLE
[Feature Request] 收集部分用户的程序

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-bbs#10]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

如果用户同意加入程序公开计划，在没有std的时候系统自动上传该用户的100分程序

**Comment by boomzero** [comment]
@PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q

**Comment by PythonSmall-Q** [comment]
upload按钮地址是啥我忘了

**Comment by PythonSmall-Q** [comment]
@boomzero

**Comment by boomzero** [comment]
https://www.xmoj.tech/userinfo.php?ByUserScript=1

**Comment by PythonSmall-Q** [comment]
服务器运行错误：TypeError: Cannot read properties of undefined (reading 'std_code')<br>服务器运行错误：TypeError: Cannot read properties of undefined (reading 'std_code')<br>服务器运行错误：TypeError: Cannot read properties of undefined (reading 'std_code')<br>服务器运行错误：TypeError: Cannot read properties of undefined (reading 'std_code')<br>服务器运行错误：TypeError: Cannot read properties of undefined (reading 'std_code')<br>服务器运行错误：TypeError: Cannot read properties of undefined (reading 'std_code')<br>服务器运行错误：TypeError: Cannot read properties of undefined (reading 'std_code')<br>服务器运行错误：TypeError: Cannot read properties of undefined (reading 'std_code')<br>服务器运行错误：TypeError: Cannot read properties of undefined (reading 'std_code')<br>服务器运行错误：TypeError: Cannot read properties of undefined (reading 'std_code')<br>服务器运行错误：TypeError: Cannot read properties of undefined (reading 'std_code')<br>服务器运行错误：TypeError: Cannot read properties of undefined (reading 'std_code')<br>服务器运行错误：TypeError: Cannot read properties of undefined (reading 'std_code')<br>服务器运行错误：TypeError: Cannot read properties of undefined (reading 'std_code')<br>服务器运行错误：TypeError: Cannot read properties of undefined (reading 'std_code')<br>

**Comment by PythonSmall-Q** [comment]
狂刷这个

**Comment by PythonSmall-Q** [comment]
炸锅了

**Comment by boomzero** [comment]
Emm

**Comment by PythonSmall-Q** [comment]
> 上传的内容不是您AC的程序，而是您AC的题目对应的用户std的程序。所以您可以放心上传，不会泄露您的代码。

好讽刺

**Comment by boomzero** [comment]
好了吗

**Comment by PythonSmall-Q** [comment]
我试试，报错了告诉你。目前没报错，10%了

**Comment by PythonSmall-Q** [comment]
数据库查询失败：Error: D1_ERROR: UNIQUE constraint failed: std_answer.problem_id<br>
@boomzero

**Comment by PythonSmall-Q** [comment]
哦又好了

**Comment by PythonSmall-Q** [comment]
好像不太稳定

**Comment by PythonSmall-Q** [comment]
经常需要刷新

**Comment by PythonSmall-Q** [comment]
有的题还是没办法upload上去，比如说1063

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-bbs/assets/106425289/3b9b0084-798a-4b2d-b287-f705896da46d)
蛤？？？？

**Comment by PythonSmall-Q** [comment]
没有code，只有code by shanwenxiao

**Comment by PythonSmall-Q** [comment]
好壮观
![image](https://github.com/XMOJ-Script-dev/XMOJ-bbs/assets/106425289/3a213f6d-0aeb-4c7a-8753-742954aef940)

**Comment by PythonSmall-Q** [comment]
@boomzero 加油呀

**Comment by boomzero** [comment]
Emm

**Comment by boomzero** [comment]
这样吧, 提交最优解

**Comment by PythonSmall-Q** [comment]
你就交我的代码

**Comment by PythonSmall-Q** [comment]
最优解有时候很怪的

**Comment by PythonSmall-Q** [comment]
我的代码好歹是人写的

**Comment by langningchen** [comment]
我来了

**Comment by langningchen** [comment]
怎么了？

**Comment by PythonSmall-Q** [comment]
> 怎么了？

没什么，就是在解决问题罢了

**Comment by langningchen** [comment]
好吧

**Comment by PythonSmall-Q** [comment]
然后我快爆炸了

**Comment by boomzero** [comment]
怎么了

**Comment by PythonSmall-Q** [comment]
改好了吗

**Comment by boomzero** [comment]
sorry, 改作文ing

<img width="1798" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-bbs/assets/85378277/5852e7f4-7fa6-4cbf-9af4-a2d41de2d459">

**Comment by PythonSmall-Q** [comment]
没事的

**Comment by boomzero** [comment]
Tommorrow, maybe

**Comment by PythonSmall-Q** [comment]
okay

**Comment by boomzero** [comment]
But I can use cheerio

**Comment by boomzero** [comment]
@PythonSmall-Q 好了! 好了! 好了!

**Comment by boomzero** [comment]
@PythonSmall-Q @PythonSmall-Q @PythonSmall-Q

**Comment by boomzero** [comment]
@PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q

**Comment by boomzero** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-bbs/assets/85378277/28387a1a-10db-4161-9092-1c01a81202c8)

**Comment by boomzero** [comment]
> @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q

**Comment by PythonSmall-Q** [comment]
？干嘛
