### ISSUE TITLE
[Feature Request] [提案] 为每一位用户使用独立token校验

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-bbs#24]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

为增加安全性，设想当每一个用户运行脚本时从服务器请求一个token（服务器端会在D1中存储，用户端在本地GM存储token和请求时间，10/15days or longer的有效时间，超过有效时间自动refresh），每一次向服务器POST时bearer里增加token，服务器校验正确就继续，否则abort并报403

### 原因

突发奇想的内容

~念念不忘，必有回响~

**Comment by boomzero** [comment]
没用。如果我是attacker, 我只需要问服务器要一个token即可

**Comment by boomzero** [comment]
你达到什么目的？remove backwards compatibility?

**Comment by boomzero** [comment]
显然你做太多语文阅读了（

**Comment by PythonSmall-Q** [comment]
额有道理

**Comment by PythonSmall-Q** [comment]
语文阅读怎么你了（doge

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-bbs/assets/106425289/966f6a36-648c-4d8a-a5c4-cbd6a929b3d7)
这么写不会报错吧，zhouyiqing想看ac代码

**Comment by PythonSmall-Q** [comment]
但感觉想做一个类似GitHub PAT一样的auth

**Comment by PythonSmall-Q** [comment]
~那GitHub怎么做的照搬就可以了呗~

**Comment by boomzero** [comment]
PHPSESSID不行吗?

**Comment by PythonSmall-Q** [comment]
okay
