### ISSUE TITLE
[Bug] 表查询没有锁定

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-bbs#3]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

`错误：数据库查询失败：Error: D1_ERROR: UNIQUE constraint failed: phpsessid.token`

原因是表被多个请求同时查询

### 重现步骤

清楚 cookies ，然后直接在讨论区刷新

**Comment by boomzero** [comment]
https://github.com/XMOJ-Script-dev/XMOJ-bbs/commit/7f9fc2981ecfca5e95cb16015b07f1a63eacc990

**Comment by boomzero** [comment]
@langningchen

**Comment by langningchen** [comment]
@boomzero 也可以
